apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test-app
spec:
  selector:
    matchLabels:
      app: argocd-test-app
  replicas: 2
  template:
    metadata:
      labels:
        app: argocd-test-app
    spec:
      containers:
      - name: argocd-test-app
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
